# coding: utf-8

"""
    Gallop API

    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@higallop.com
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="Gallop API",
    author="OpenAPI Generator community",
    author_email="support@higallop.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Gallop API"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="UNLICENSED",
    long_description="""\
    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501
    """
)
