# coding: utf-8

"""
    Gallop API

    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@higallop.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.analytics_eth_get_collection_floor_price_ohlc.post import GetEthCollectionFloorPriceOhlc
from openapi_client.paths.insights_eth_get_collection_forecasts.post import GetEthCollectionForecasts
from openapi_client.paths.analytics_eth_get_collection_listings_ohlc.post import GetEthCollectionListingsOhlc
from openapi_client.paths.data_eth_get_collection_owners.post import GetEthCollectionOwners
from openapi_client.paths.analytics_eth_get_collection_price_diff.post import GetEthCollectionPriceDiff
from openapi_client.paths.analytics_eth_get_collection_sales_ohlc.post import GetEthCollectionSalesOhlc
from openapi_client.paths.analytics_eth_get_collection_summary.post import GetEthCollectionSummary
from openapi_client.paths.data_eth_get_collection_transactions.post import GetEthCollectionTransactions
from openapi_client.paths.data_eth_get_collections.post import GetEthCollections
from openapi_client.paths.insights_eth_get_custom_collection_risk.post import GetEthCustomCollectionRisk
from openapi_client.paths.insights_eth_get_custom_token_risk.post import GetEthCustomTokenRisk
from openapi_client.paths.insights_eth_get_default_collection_risk.post import GetEthDefaultCollectionRisk
from openapi_client.paths.insights_eth_get_default_token_risk.post import GetEthDefaultTokenRisk
from openapi_client.paths.data_eth_get_ens_lookup.post import GetEthEnsLookup
from openapi_client.paths.data_eth_get_historical_events.post import GetEthHistoricalEvents
from openapi_client.paths.data_eth_get_historical_transactions.post import GetEthHistoricalTransactions
from openapi_client.paths.analytics_eth_get_leader_board.post import GetEthLeaderBoard
from openapi_client.paths.data_eth_get_marketplace_data.post import GetEthMarketplaceData
from openapi_client.paths.data_eth_get_marketplace_floor_price.post import GetEthMarketplaceFloorPrice
from openapi_client.paths.data_eth_get_marketplace_trait_data.post import GetEthMarketplaceTraitData
from openapi_client.paths.analytics_eth_get_rarity.post import GetEthRarity
from openapi_client.paths.insights_eth_get_token_appraisal.post import GetEthTokenAppraisal
from openapi_client.paths.insights_eth_get_token_forecasts.post import GetEthTokenForecasts
from openapi_client.paths.analytics_eth_get_token_summary.post import GetEthTokenSummary
from openapi_client.paths.data_eth_get_token_transactions.post import GetEthTokenTransactions
from openapi_client.paths.data_eth_get_tokens.post import GetEthTokens
from openapi_client.paths.insights_eth_get_wallet_labels.post import GetEthWalletLabels
from openapi_client.paths.data_eth_get_wallet_nfts.post import GetEthWalletNfts
from openapi_client.paths.data_eth_get_wallet_transactions.post import GetEthWalletTransactions
from openapi_client.paths.analytics_eth_get_wash_trade.post import GetEthWashTrade
from openapi_client.paths.analytics_eth_get_wash_transactions.post import GetEthWashTransactions


class EthereumApi(
    GetEthCollectionFloorPriceOhlc,
    GetEthCollectionForecasts,
    GetEthCollectionListingsOhlc,
    GetEthCollectionOwners,
    GetEthCollectionPriceDiff,
    GetEthCollectionSalesOhlc,
    GetEthCollectionSummary,
    GetEthCollectionTransactions,
    GetEthCollections,
    GetEthCustomCollectionRisk,
    GetEthCustomTokenRisk,
    GetEthDefaultCollectionRisk,
    GetEthDefaultTokenRisk,
    GetEthEnsLookup,
    GetEthHistoricalEvents,
    GetEthHistoricalTransactions,
    GetEthLeaderBoard,
    GetEthMarketplaceData,
    GetEthMarketplaceFloorPrice,
    GetEthMarketplaceTraitData,
    GetEthRarity,
    GetEthTokenAppraisal,
    GetEthTokenForecasts,
    GetEthTokenSummary,
    GetEthTokenTransactions,
    GetEthTokens,
    GetEthWalletLabels,
    GetEthWalletNfts,
    GetEthWalletTransactions,
    GetEthWashTrade,
    GetEthWashTransactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
