# coding: utf-8

"""
    Gallop API

    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@higallop.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.insights_pol_get_collection_forecasts.post import GetPolCollectionForecasts
from openapi_client.paths.data_pol_get_collection_owners.post import GetPolCollectionOwners
from openapi_client.paths.analytics_pol_get_collection_price_diff.post import GetPolCollectionPriceDiff
from openapi_client.paths.analytics_pol_get_collection_sales_ohlc.post import GetPolCollectionSalesOhlc
from openapi_client.paths.analytics_pol_get_collection_summary.post import GetPolCollectionSummary
from openapi_client.paths.data_pol_get_collection_traits.post import GetPolCollectionTraits
from openapi_client.paths.data_pol_get_collection_transactions.post import GetPolCollectionTransactions
from openapi_client.paths.data_pol_get_collections.post import GetPolCollections
from openapi_client.paths.insights_pol_get_custom_collection_risk.post import GetPolCustomCollectionRisk
from openapi_client.paths.insights_pol_get_custom_token_risk.post import GetPolCustomTokenRisk
from openapi_client.paths.insights_pol_get_default_collection_risk.post import GetPolDefaultCollectionRisk
from openapi_client.paths.insights_pol_get_default_token_risk.post import GetPolDefaultTokenRisk
from openapi_client.paths.data_pol_get_historical_transactions.post import GetPolHistoricalTransactions
from openapi_client.paths.analytics_pol_get_leader_board.post import GetPolLeaderBoard
from openapi_client.paths.data_pol_get_marketplace_data.post import GetPolMarketplaceData
from openapi_client.paths.data_pol_get_marketplace_floor_price.post import GetPolMarketplaceFloorPrice
from openapi_client.paths.analytics_pol_get_rarity.post import GetPolRarity
from openapi_client.paths.insights_pol_get_token_appraisal.post import GetPolTokenAppraisal
from openapi_client.paths.insights_pol_get_token_forecasts.post import GetPolTokenForecasts
from openapi_client.paths.analytics_pol_get_token_summary.post import GetPolTokenSummary
from openapi_client.paths.data_pol_get_token_transactions.post import GetPolTokenTransactions
from openapi_client.paths.data_pol_get_tokens.post import GetPolTokens
from openapi_client.paths.insights_pol_get_wallet_labels.post import GetPolWalletLabels
from openapi_client.paths.data_pol_get_wallet_nfts.post import GetPolWalletNfts
from openapi_client.paths.data_pol_get_wallet_transactions.post import GetPolWalletTransactions
from openapi_client.paths.analytics_pol_get_wash_trade.post import GetPolWashTrade
from openapi_client.paths.analytics_pol_get_wash_transactions.post import GetPolWashTransactions


class PolygonApi(
    GetPolCollectionForecasts,
    GetPolCollectionOwners,
    GetPolCollectionPriceDiff,
    GetPolCollectionSalesOhlc,
    GetPolCollectionSummary,
    GetPolCollectionTraits,
    GetPolCollectionTransactions,
    GetPolCollections,
    GetPolCustomCollectionRisk,
    GetPolCustomTokenRisk,
    GetPolDefaultCollectionRisk,
    GetPolDefaultTokenRisk,
    GetPolHistoricalTransactions,
    GetPolLeaderBoard,
    GetPolMarketplaceData,
    GetPolMarketplaceFloorPrice,
    GetPolRarity,
    GetPolTokenAppraisal,
    GetPolTokenForecasts,
    GetPolTokenSummary,
    GetPolTokenTransactions,
    GetPolTokens,
    GetPolWalletLabels,
    GetPolWalletNfts,
    GetPolWalletTransactions,
    GetPolWashTrade,
    GetPolWashTransactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
