# coding: utf-8

"""
    Gallop API

    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@higallop.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.data_sol_get_account_nfts.post import GetSolAccountNfts
from openapi_client.paths.insights_sol_get_collection_forecasts.post import GetSolCollectionForecasts
from openapi_client.paths.analytics_sol_get_collection_price_diff.post import GetSolCollectionPriceDiff
from openapi_client.paths.analytics_sol_get_collection_sales_ohlc.post import GetSolCollectionSalesOhlc
from openapi_client.paths.analytics_sol_get_collection_summary.post import GetSolCollectionSummary
from openapi_client.paths.data_sol_get_collection_traits.post import GetSolCollectionTraits
from openapi_client.paths.data_sol_get_collection_transactions.post import GetSolCollectionTransactions
from openapi_client.paths.data_sol_get_collections.post import GetSolCollections
from openapi_client.paths.insights_sol_get_custom_collection_risk.post import GetSolCustomCollectionRisk
from openapi_client.paths.insights_sol_get_custom_token_risk.post import GetSolCustomTokenRisk
from openapi_client.paths.insights_sol_get_default_collection_risk.post import GetSolDefaultCollectionRisk
from openapi_client.paths.insights_sol_get_default_token_risk.post import GetSolDefaultTokenRisk
from openapi_client.paths.data_sol_get_historical_transactions.post import GetSolHistoricalTransactions
from openapi_client.paths.data_sol_get_marketplace_data.post import GetSolMarketplaceData
from openapi_client.paths.data_sol_get_marketplace_floor_price.post import GetSolMarketplaceFloorPrice
from openapi_client.paths.data_sol_get_marketplace_trait_data.post import GetSolMarketplaceTraitData
from openapi_client.paths.data_sol_get_nft_account.post import GetSolNftAccount
from openapi_client.paths.analytics_sol_get_rarity.post import GetSolRarity
from openapi_client.paths.insights_sol_get_token_appraisal.post import GetSolTokenAppraisal
from openapi_client.paths.insights_sol_get_token_forecasts.post import GetSolTokenForecasts
from openapi_client.paths.analytics_sol_get_token_summary.post import GetSolTokenSummary
from openapi_client.paths.data_sol_get_token_transactions.post import GetSolTokenTransactions
from openapi_client.paths.data_sol_get_tokens.post import GetSolTokens
from openapi_client.paths.analytics_sol_get_wash_trade.post import GetSolWashTrade
from openapi_client.paths.analytics_sol_get_wash_transactions.post import GetSolWashTransactions


class SolanaApi(
    GetSolAccountNfts,
    GetSolCollectionForecasts,
    GetSolCollectionPriceDiff,
    GetSolCollectionSalesOhlc,
    GetSolCollectionSummary,
    GetSolCollectionTraits,
    GetSolCollectionTransactions,
    GetSolCollections,
    GetSolCustomCollectionRisk,
    GetSolCustomTokenRisk,
    GetSolDefaultCollectionRisk,
    GetSolDefaultTokenRisk,
    GetSolHistoricalTransactions,
    GetSolMarketplaceData,
    GetSolMarketplaceFloorPrice,
    GetSolMarketplaceTraitData,
    GetSolNftAccount,
    GetSolRarity,
    GetSolTokenAppraisal,
    GetSolTokenForecasts,
    GetSolTokenSummary,
    GetSolTokenTransactions,
    GetSolTokens,
    GetSolWashTrade,
    GetSolWashTransactions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
