# coding: utf-8

"""
    Gallop API

    Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@higallop.com
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.data_skn_get_marketplace_data.post import GetSknMarketplaceData
from openapi_client.paths.data_skn_get_marketplace_floor_price.post import GetSknMarketplaceFloorPrice


class StarknetApi(
    GetSknMarketplaceData,
    GetSknMarketplaceFloorPrice,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
